iVERSION CONTROL SYSTEM IS ALSO KNOWN AS SOFTWARE CONFIGURATION MANAGEMENT(SCM) OR SOURCE CODE MANAGEMENT(SCM)

--WHY WE NEED VERSION CONTROL SYSTEM?
BEING A DEVELOPER WE HAVE TO WRITE SEVERAL FILES WHICH CONTAINS SOURCE CODE TO GET THE OLD VERSIONS OF CODES WE MAY NEED
THE VERSION CONTROL TOOL.

--GIT(new version)
GIT IS A DISTRIBUTED VERSION CONTROL TOOL

https://github.com/hemantkrbehera91/DATAENGG.git

1>GIT CLONE- TO CREATE A NEW LOCAL REPOSITORY FROM THE REMOTE REPOSITORY
2>GIT ADD- TO ADD FILES FROM WORKING DIRECTORYU TO STAGING AREA
3>GIT COMMIT-to commit changes from staging area to local repository
4>GIT PUSH-to move files from local repository to global repository

5>GIT PULL

https://github.com/hemantkrbehera91/dreamit.git

my git version worked fine
